WebULI/Areas/Admin/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebULI.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using ledsangviet.com.CodeHelper;

namespace WebULI.Areas.Admin.Controllers
{
    public class SliderController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/Slider
        public async Task<ActionResult> Index()
        {
            var applicationSliders = db.Sliders.Include(a => a.User);
            return View(await applicationSliders.ToListAsync());
        }

        // GET: Admin/Slider/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationSlider applicationSlider = await db.Sliders.FindAsync(id);
            if (applicationSlider == null)
            {
                return HttpNotFound();
            }
            return View(applicationSlider);
        }

        // GET: Admin/Slider/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Slider/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ImageUrl,Title,ShowOnHome,UpdateTime")] ApplicationSlider applicationSlider)
        {
            if (ModelState.IsValid)
            {
                applicationSlider.UserId = User.Identity.GetUserId();
                db.Sliders.Add(applicationSlider);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(applicationSlider);
        }

        // GET: Admin/Slider/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationSlider applicationSlider = await db.Sliders.FindAsync(id);
            if (applicationSlider == null)
            {
                return HttpNotFound();
            }
            return View(applicationSlider);
        }

        // POST: Admin/Slider/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,ImageUrl,Title,ShowOnHome,UpdateTime")] ApplicationSlider applicationSlider)
        {
            if (ModelState.IsValid)
            {
                applicationSlider.UserId = User.Identity.GetUserId();
                db.Entry(applicationSlider).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(applicationSlider);
        }

        // GET: Admin/Slider/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationSlider applicationSlider = await db.Sliders.FindAsync(id);
            if (applicationSlider == null)
            {
                return HttpNotFound();
            }
            return View(applicationSlider);
        }

        // POST: Admin/Slider/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            ApplicationSlider applicationSlider = await db.Sliders.FindAsync(id);
            db.Sliders.Remove(applicationSlider);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<JsonResult> ChangeImage(Guid? id)
        {
            if (Request != null)
            {
                HttpPostedFileBase file = Request.Files["image"];
                if ((file != null) && (file.ContentLength > 0) && !string.IsNullOrEmpty(file.FileName))
                {
                    try
                    {
                        string fileName = file.FileName;
                        string fileContentType = file.ContentType;
                        byte[] fileBytes = new byte[file.ContentLength];
                        var data = file.InputStream.Read(fileBytes, 0, Convert.ToInt32(file.ContentLength));

                        try
                        {
                            string _FileName = GuidComb.GenerateComb() + Path.GetExtension(file.FileName);
                            if (Directory.Exists(Server.MapPath("~/Uploads")) == false)
                            {
                                Directory.CreateDirectory(Server.MapPath("~/Uploads"));
                            }
                            string _path = Path.Combine(Server.MapPath("~/Uploads"), _FileName);
                            // lưu file và server
                            file.SaveAs(_path);

                            var model = await db.Sliders.FindAsync(id);
                            if (model != null)
                            {
                                // Xóa file cũ
                                string del_file = Path.Combine(Server.MapPath(model.ImageUrl));
                                if (System.IO.File.Exists(del_file))
                                {
                                    System.IO.File.Delete(del_file);
                                }
                                model.ImageUrl = "/Uploads/" + _FileName;
                                await db.SaveChangesAsync();
                                return Json(new { status = true, mes = "Thay đổi thành công" }, JsonRequestBehavior.AllowGet);
                            }
                            return Json(new { status = true, mes = "Thay đổi thất bại" }, JsonRequestBehavior.AllowGet);
                        }
                        catch { }
                    }
                    catch (Exception ex)
                    {
                        return Json(new { status = false, data = ex.Message }, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            return Json(new { status = false, mes = "Có lỗi xảy ra" }, JsonRequestBehavior.AllowGet);
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebULI/Controllers/PartialViewController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebULI.Models;

namespace WebULI.Controllers
{
    public class PartialViewController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: PartialView
        [ChildActionOnly]
        public PartialViewResult _Topbar()
        {
            return PartialView();
        }
        // GET: PartialView
        [ChildActionOnly]
        public PartialViewResult _Header()
        {
            return PartialView();
        }
        // GET: PartialView
        [ChildActionOnly]
        public PartialViewResult  _Slider()
        {
            ViewBag.Sliders = db.Sliders.Where(x => x.ShowOnHome == true).ToList();
            return PartialView();
        }

        // GET: PartialView
        [ChildActionOnly]
        public PartialViewResult _Footer()
        {
            return PartialView();
        }

        // GET: PartialView
        [ChildActionOnly]
        public PartialViewResult _Sidebar()
        {
            return PartialView();
        }
    }
}

WebULI/Views/Shared/_ClientLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="ULI">
    <meta name="author" content="chuongnh">
    <meta name="keyword" content="ULI">
    <title>@ViewBag.Title - ULI</title>
    <!-- <link rel="shortcut icon" href="assets/ico/favicon.png"> -->
    <!-- Icons -->
    <link href="~/Areas/Admin/Assets/vendors/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Areas/Admin/Assets/vendors/css/simple-line-icons.min.css" rel="stylesheet">
    <!-- Main styles for this application -->
    <link href="~/Areas/Admin/Assets/css/style.css" rel="stylesheet">
    <!-- Styles required by this views -->
</head>
<body class="app flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card-group mb-0">
                    <div class="card p-4">
                        <div class="card-body">
                           @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap and necessary plugins -->
    <script src="~/Areas/Admin/Assets/vendors/js/jquery.min.js"></script>
    <script src="~/Areas/Admin/Assets/vendors/js/popper.min.js"></script>
    <script src="~/Areas/Admin/Assets/vendors/js/bootstrap.min.js"></script>
</body>
</html>

WebULI/Views/Shared/_Footer.cshtml
<footer>
    <div class="footer">
        <div class="container">
            <div class="footer-wrapper">
                <div class="row">

                    <!-- Footer Col. -->
                    <div class="col-md-3 col-sm-3 footer-col">
                        <div class="footer-content">
                            <div class="footer-title">
                                Giới thiệu ULI
                            </div>
                            @*<div class="footer-content-logo">
                                   <img src="~/Assets/images/main_logo.png" alt="" />
                                </div>*@
                            <div class="footer-content-text">
                                <p>
                                    ULI được thành lập với với sứ mạng tiếp sức cho thế hệ trẻ Việt Nam trên con đường tiến ra thế giới bằng hai công cụ toàn cầu, tiếng Anh và Khoa học máy tính.
                                </p>
                                <p>
                                    Với kiến thức Khoa học máy tính và tiếng Anh, các bạn trẻ sẽ tự tin và có đủ cơ hội để phát triển nghề nghiệp trong thời đại công nghệ 4.0 và toàn cầu hóa.
                                </p>
                            </div>
                        </div>
                    </div>
                    <!-- //Footer Col.// -->
                    <!-- Footer Col. -->
                    <div class="col-md-3 col-sm-3 footer-col">
                        <div class="footer-title">
                            Tin gần đây
                        </div>
                        <div class="footer-content">
                            <ul class="posts-list">
                                @for (int i = 0; i < 2; i++)
                                {
                                    <li>
                                        <div class="posts-list-thumbnail">
                                            <a href="#">
                                                <img src="~/Assets/media/blog1-thumb.jpg" alt="" />
                                            </a>
                                        </div>
                                        <div class="posts-list-content">
                                            <a href="#" class="posts-list-title">Tuyển dụng Lập trình viên Java/ .Net/ PHP </a>
                                            <small class="posts-list-meta">
                                                July 30, 2013
                                            </small>
                                        </div>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                    <!-- //Footer Col.// -->
                    <!-- Footer Col. -->
                    <div class="col-md-3 col-sm-3 footer-col">
                        <div class="footer-title">
                            Liên kết
                        </div>
                        <div class="footer-content">
                            <ul class="footer-category-list">
                                <li><a href="#">Giới thiệu</a> </li>
                                <li><a href="#">Chương trình đào tạo</a> </li>
                                <li><a href="#">Lịch khai giảng</a> </li>
                                <li><a href="#">Liên hệ</a> </li>
                                <li><a href="#">Tin mới</a> </li>
                                <li><a href="#">Testimonial</a> </li>
                            </ul>
                        </div>
                    </div>
                    <!-- //Footer Col.// -->
                    <!-- Footer Col. -->
                    <div class="col-md-3 col-sm-3 footer-col">
                        <div class="footer-title">
                            Testimonials
                        </div>
                        <div class="footer-content">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="testimonial">
                                        <div class="testimonial-content cycle-slideshow" data-cycle-slides="> .testimonial-item" data-cycle-swipe="true">
                                            @for (int i = 0; i < 2; i++)
                                            {
                                                <div class="testimonial-item">
                                                    <div class="testimonial-person-pic">
                                                        <img src="~/Assets/media/team1.jpg" alt="Jane Doe" class="img-responsive" />
                                                    </div>
                                                    <div class="testimonial-text" style="color:black">
                                                        Lorem ipsum dolor sit amet, feugiat delicata liberavisse id cum, no quo maiorum intellegebat, liber regione eu sit.
                                                    </div>
                                                    <div class="testimonial-by">
                                                        <span class="testimonial-by-name">Nguyễn Văn Dậu,</span>
                                                        <span class="testimonial-by-position">Học viên</span>
                                                    </div>
                                                </div>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 center-text">
                        <div class="copyright-text">&copy; 2017 ULI By <a href="https://hcmuteteam.com/chuongnh" target="_blank">HCMUTE TEAM</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
    </div>

WebULI/Views/Shared/_Header.cshtml
<header id="header">
    <div class="container">
        <div class="row header">
            <!-- Logo -->
            <div class="col-xs-2 logo">
                <a href="/">
                    <img src="~/Assets/images/main_logo.png" alt="Kanzi HTML5 Template" />
                </a>
            </div>
            <!-- //Logo// -->
            <!-- Navigation File -->
            <div class="col-md-10">
                <!-- Mobile Button Menu -->
                <div class="mobile-menu-button">
                    <i class="fa fa-list-ul"></i>
                </div>
                <!-- //Mobile Button Menu// -->


                <nav>
                    <ul class="navigation">
                        <li>
                            <a href="/ULIMember">
                                <span class="label-nav">
                                    Giới thiệu
                                </span>
                            </a>
                            <ul>
                                <li>
                                    <a href="#"> Tầm nhìn & Định hướng </a>
                                </li>
                                <li>
                                    <a href="#">Các thành viên</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="/#">
                                <span class="label-nav">
                                   Chương trình đào tạo
                                </span>
                            </a>
                            <ul>
                                <li>
                                    <a href="#">Chương trình học</a>
                                </li>
                                <li>
                                    <a href="#">Ban giảng huấn</a>
                                </li>
                                <li>
                                    <a href="#">Cách đăng ký</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="/UpCommingClasses">
                                <span class="label-nav">
                                    Lịch khai giảng
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="/Contact">
                                <span class="label-nav">
                                    Liên hệ
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="/News">
                                <span class="label-nav">
                                    Tin mới
                                </span>
                            </a>
                            <ul>
                                <li>
                                    <a href="#">Jobs</a>
                                </li>
                                <li>
                                    <a href="#">Sự kiện</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="/#">
                                <span class="label-nav">
                                    Testimonial
                                </span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- Mobile Nav. Container -->
                <ul class="mobile-nav">
                    <li class="responsive-searchbox">
                        <!-- Responsive Nave -->
                        <form action="#" method="get">
                            <input type="text" class="searchbox-inputtext" id="searchbox-inputtext-mobile" name="s" />
                            <button class="icon-search"></button>
                        </form>
                        <!-- //Responsive Nave// -->
                    </li>
                </ul>
                <!-- //Mobile Nav. Container// -->
            </div>
            <!-- Nav -->
        </div>

    </div>
</header>

WebULI/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebULI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="ULI">
    <meta name="author" content="chuongnh">
    <meta name="keyword" content="ULI">

    <title>@ViewBag.Title - ULI</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Assets/css/revolution_settings.css">
    <link rel="stylesheet" href="~/Assets/css/bootstrap.css">
    <link rel="stylesheet" href="~/Assets/css/font-awesome.css">
    <link rel="stylesheet" href="~/Assets/css/axfont.css">
    <link rel="stylesheet" href="~/Assets/css/tipsy.css">
    <link rel="stylesheet" href="~/Assets/css/prettyPhoto.css">
    <link rel="stylesheet" href="~/Assets/css/isotop_animation.css">
    <link rel="stylesheet" href="~/Assets/css/animate.css">

    <!-- remprod -->
    <link rel="stylesheet" href="~/Assets/css/_colorpicker.css">
    <!-- end remprod -->
    <link href='~/Assets/css/style.css' rel='stylesheet' type='text/css'>
    <link href='~/Assets/css/responsive.css' rel='stylesheet' type='text/css'>
    <link href="~/Assets/css/skins/light-blue.css" rel='stylesheet' type='text/css' id="skin-file">
    <!-- remprod -->
    @* <style type="text/css" id="skin-chooser-css">*@
    </style>
    <!-- end remprod -->
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script>
    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600' rel='stylesheet' type='text/css'>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="js/respond.js"></script>
    <![endif]-->
    @*<link rel="stylesheet" href="~/Assets/css/color-chooser.css">*@
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script type="text/javascript">
        var $default_skin = "light-blue";
    </script>
</head>
<body class="bgpattern-pw-pattern">
    <div id="wrapper" class="wide">
        <div class="top_wrapper">
            @{ Html.RenderAction("_Topbar", "PartialView", null);}
            <!-- Header -->
            @{ Html.RenderAction("_Header", "PartialView", null);}
            <!-- //Header// -->
            @*@{ Html.RenderAction("_Slider", "PartialView", null);}*@
        </div>
   
        @RenderBody()
        <!--.content-wrapper end -->

        @{ Html.RenderAction("_Footer", "PartialView", null);}
        <div id='bttop'><i class="glyphicon glyphicon-chevron-up"></i></div>
    </div>
    <!-- wrapper end -->
    <script type="text/javascript" src="~/Assets/js/_jq.js"></script>
    <script type="text/javascript" src="~/Assets/js/_jquery.placeholder.js"></script>
    <!-- remprod -->
    <script type="text/javascript" src="~/Assets/js/_colorpicker.js"></script>
    <script type="text/javascript" src="~/Assets/js/_handlebars.js"></script>
    <script type="text/javascript" src="~/Assets/js/_skins.js"></script>
    @*<script type="text/javascript" src="~/Assets/js/_skinchooser.js"></script>*@
    <!-- end remprod -->
    <script src="~/Assets/js/activeaxon_menu.js" type="text/javascript"></script>
    <script src="~/Assets/js/animationEnigne.js" type="text/javascript"></script>
    <script src="~/Assets/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Assets/js/ie-fixes.js" type="text/javascript"></script>
    <script src="~/Assets/js/jq.appear.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.base64.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.carouFredSel-6.2.1-packed.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.cycle.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.cycle2.carousel.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.easing.1.3.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.easytabs.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.infinitescroll.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.isotope.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.prettyPhoto.js" type="text/javascript"></script>
    <script src="~/Assets/js/jQuery.scrollPoint.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.themepunch.plugins.min.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.themepunch.revolution.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.tipsy.js" type="text/javascript"></script>
    <script src="~/Assets/js/jquery.validate.js" type="text/javascript"></script>
    <script src="~/Assets/js/jQuery.XDomainRequest.js" type="text/javascript"></script>
    <script src="~/Assets/js/kanzi.js" type="text/javascript"></script>
    <script src="~/Assets/js/retina.js" type="text/javascript"></script>
    <script src="~/Assets/js/timeago.js" type="text/javascript"></script>
    <script src="~/Assets/js/tweetable.jquery.js" type="text/javascript"></script>

    <script src="~/Scripts/site.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

WebULI/Views/Shared/_Sidebar.cshtml
<div class="sidebar">

    <!-- Sidebar Block -->
    <div class="sidebar-block">
        <div class="sidebar-content tags blog-search">
            <form action="#" method="post">
                <div class="input-group">
                    <input type="text" name="q" class="form-control blog-search-input text-input" placeholder="Tìm kiếm bài viết.." />
                    <span class="input-group-addon">
                        <button class="blog-search-button icon-search "></button>
                    </span>
                </div>
            </form>
        </div>
    </div>
    <!-- Sidebar Block -->
    <!-- Sidebar Block -->
    @*<div class="sidebar-block">
        <h3 class="h3-sidebar-title sidebar-title">
            tags
        </h3>
        <div class="sidebar-content tags">
            <a href="#">HTML5</a>
            <a href="#">CSS3</a>
            <a href="#">jQuery</a>
            <a href="#">JavaScript</a>
            <a href="#">WordPress</a>
            <a href="#">PHP</a>
            <a href="#">CSS</a>
            <a href="#">Social Media</a>
            <a href="#">HTML</a>
        </div>
    </div>*@
    <!-- Sidebar Block -->
    <!-- Sidebar Block -->
    <div class="sidebar-block">
        <h3 class="h3-sidebar-title sidebar-title" style="padding-top:5px">
           Bài viết gần đây
        </h3>
        <div class="sidebar-content">
            <ul class="posts-list">
                <li>
                    <div class="posts-list-thumbnail">
                        <a href="#">
                            <img src="~/Assets/media/blog1-thumb.jpg" alt="" />
                        </a>
                    </div>
                    <div class="posts-list-content">
                        <a href="#" class="posts-list-title">Sidebar post example </a>
                        <span class="posts-list-meta">
                            July 30, 2013
                        </span>
                    </div>
                </li>
                <li>
                    <div class="posts-list-thumbnail">
                        <a href="#">
                            <img src="~/Assets/media/blog2-thumb.jpg" alt="" />
                        </a>
                    </div>
                    <div class="posts-list-content">
                        <a href="#" class="posts-list-title">Sidebar post example </a>
                        <span class="posts-list-meta">
                            July 30, 2013
                        </span>
                    </div>
                </li>
                <li>
                    <div class="posts-list-thumbnail">
                        <a href="#">
                            <img src="~/Assets/media/blog3-thumb.jpg" alt="" />
                        </a>
                    </div>
                    <div class="posts-list-content">
                        <a href="#" class="posts-list-title">Sidebar post example </a>
                        <span class="posts-list-meta">
                            July 30, 2013
                        </span>
                    </div>
                </li>
                <li>
                    <div class="posts-list-thumbnail">
                        <a href="#">
                            <img src="~/Assets/media/blog4-thumb.jpg" alt="" />
                        </a>
                    </div>
                    <div class="posts-list-content">
                        <a href="#" class="posts-list-title">Sidebar post example </a>
                        <span class="posts-list-meta">
                            July 30, 2013
                        </span>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <!-- Sidebar Block -->
</div>